### ISSUE TITLE
Go Rewrite

### ISSUE THREAD

**Issue by lexman02** [lexman02/intralab#13]
Rewrite the backend in Go and the Frontend in Svelte for better performance and easier containerization. The primary goal of this issue is to track progress until feature parity with original implementation.

- Backend (Go)
  - [chi](https://github.com/go-chi/chi) (router)
  - [viper](https://github.com/spf13/viper) (configuration)
  - [BoltDB](https://github.com/boltdb/bolt/tree/master) (embedded database)
  - [logrus](https://github.com/sirupsen/logrus) (logging) - to be implemented
- Frontend (Svelte)
  - [TailwindCSS](https://tailwindcss.com/docs)
  - [svelte-routing](https://github.com/EmilTholin/svelte-routing/tree/master)

#### TO-DO
- [x] Basic routing implemented
- [x] Blade frontend converted to svelte components
- [ ] #15
- [ ] #14
- [ ] Original functionality to implement (in order of importance)
  - [ ] #5 
  - [ ] #10 
  - [ ] #12
